/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.yoko.simple;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the Celtix 1.1-SNAPSHOT
 * Thu Jun 15 16:22:57 NDT 2006
 * Generated source version: 1.1-SNAPSHOT
 * 
 */

@WebService(wsdlLocation = "/home/dmiddlem/dev/yoko/trunk/bindings/src/test/resources/wsdl/simpleIdl.wsdl", targetNamespace = "http://yoko.apache.org/simple", name = "Simple")

public interface Simple {

    @ResponseWrapper(targetNamespace = "http://yoko.apache.org/simple/types", className = "org.apache.yoko.simple.types.TestSimpleMethodResult", localName = "testSimpleMethodResult")
    @RequestWrapper(targetNamespace = "http://yoko.apache.org/simple/types", className = "org.apache.yoko.simple.types.TestSimpleMethod", localName = "testSimpleMethod")
    @WebResult(targetNamespace = "http://yoko.apache.org/simple/types", name = "return")
    @WebMethod(operationName = "testSimpleMethod")
    public boolean testSimpleMethod(
        @WebParam(targetNamespace = "http://yoko.apache.org/simple/types", name = "param1")
        java.lang.String param1
    );
}
