/*
 * Copyright 2022 IBM Corporation and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an \"AS IS\" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package test.rmi;

/**
* test/rmi/SampleCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from SampleCorbaObject.idl
* Tuesday, 28 April 2015 17:10:49 o'clock BST
*/

public final class SampleCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public test.rmi.SampleCorba value = null;

  public SampleCorbaHolder ()
  {
  }

  public SampleCorbaHolder (test.rmi.SampleCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = test.rmi.SampleCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    test.rmi.SampleCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return test.rmi.SampleCorbaHelper.type ();
  }

}
