package acme;


/**
* acme/CatalogueHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 13:10:15 o'clock BST
*/

abstract public class CatalogueHelper
{
  private static String  _id = "IDL:acme/Catalogue:1.0";

  public static void insert (org.omg.CORBA.Any a, acme.Catalogue that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static acme.Catalogue extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (acme.CatalogueHelper.id (), "Catalogue");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static acme.Catalogue read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CatalogueStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, acme.Catalogue value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static acme.Catalogue narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof acme.Catalogue)
      return (acme.Catalogue)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      acme._CatalogueStub stub = new acme._CatalogueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static acme.Catalogue unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof acme.Catalogue)
      return (acme.Catalogue)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      acme._CatalogueStub stub = new acme._CatalogueStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
