package acme;

/**
* acme/CatalogueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 13:10:15 o'clock BST
*/

public final class CatalogueHolder implements org.omg.CORBA.portable.Streamable
{
  public acme.Catalogue value = null;

  public CatalogueHolder ()
  {
  }

  public CatalogueHolder (acme.Catalogue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = acme.CatalogueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    acme.CatalogueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return acme.CatalogueHelper.type ();
  }

}
