package acme;


/**
* acme/CatalogueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 13:10:15 o'clock BST
*/

public interface CatalogueOperations 
{
  void addProduct (acme.Product product) throws acme.PRODUCT_TOO_EXIST;
  acme.Product[] getProducts ();
  acme.Product findProduct (String name) throws acme.PRODUCT_NOT_EXIST;
} // interface CatalogueOperations
