package acme;


/**
* acme/CataloguePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 13:10:15 o'clock BST
*/

public class CataloguePOATie extends CataloguePOA
{

  // Constructors

  public CataloguePOATie ( acme.CatalogueOperations delegate ) {
      this._impl = delegate;
  }
  public CataloguePOATie ( acme.CatalogueOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public acme.CatalogueOperations _delegate() {
      return this._impl;
  }
  public void _delegate (acme.CatalogueOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void addProduct (acme.Product product) throws acme.PRODUCT_TOO_EXIST
  {
    _impl.addProduct(product);
  } // addProduct

  public acme.Product[] getProducts ()
  {
    return _impl.getProducts();
  } // getProducts

  public acme.Product findProduct (String name) throws acme.PRODUCT_NOT_EXIST
  {
    return _impl.findProduct(name);
  } // findProduct

  private acme.CatalogueOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CataloguePOATie
