package acme;

/**
* acme/ProductHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 12:41:09 o'clock BST
*/

public final class ProductHolder implements org.omg.CORBA.portable.Streamable
{
  public acme.Product value = null;

  public ProductHolder ()
  {
  }

  public ProductHolder (acme.Product initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = acme.ProductHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    acme.ProductHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return acme.ProductHelper.type ();
  }

}
