package acme;


/**
* acme/Product.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 12:41:09 o'clock BST
*/

public final class Product implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public float price = (float)0;

  public Product ()
  {
  } // ctor

  public Product (String _name, float _price)
  {
    name = _name;
    price = _price;
  } // ctor

} // class Product
