package acme;


/**
* acme/ProductListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 13:10:15 o'clock BST
*/

public final class ProductListHolder implements org.omg.CORBA.portable.Streamable
{
  public acme.Product value[] = null;

  public ProductListHolder ()
  {
  }

  public ProductListHolder (acme.Product[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = acme.ProductListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    acme.ProductListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return acme.ProductListHelper.type ();
  }

}
