package acme;


/**
* acme/PRODUCT_NOT_EXIST.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idl/acme.idl
* Thursday, 25 May 2023 13:10:15 o'clock BST
*/

public final class PRODUCT_NOT_EXIST extends org.omg.CORBA.UserException
{
  public String productName = null;

  public PRODUCT_NOT_EXIST ()
  {
    super(PRODUCT_NOT_EXISTHelper.id());
  } // ctor

  public PRODUCT_NOT_EXIST (String _productName)
  {
    super(PRODUCT_NOT_EXISTHelper.id());
    productName = _productName;
  } // ctor


  public PRODUCT_NOT_EXIST (String $reason, String _productName)
  {
    super(PRODUCT_NOT_EXISTHelper.id() + "  " + $reason);
    productName = _productName;
  } // ctor

} // class PRODUCT_NOT_EXIST
